name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: read

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
      - name: Coverage
        run: npm run coverage
      - name: Archive coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
      - name: Generate Release Notes
        id: notes
        run: |
          TAG=${GITHUB_REF##*/}
          PREV=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo '')
          if [ -n "${PREV}" ]; then
            RANGE="${PREV}..${TAG}"
          else
            RANGE="${TAG}"
          fi
          echo "Changes:\n" > RELEASE_NOTES.md
          git log --pretty=format:'- %s (%h)' ${RANGE} >> RELEASE_NOTES.md || true
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          cat RELEASE_NOTES.md >> $GITHUB_OUTPUT
          echo "\nEOF" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.notes.outputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
